CREATE TABLE IF NOT EXISTS crisis.tweets (
    id SERIAL PRIMARY KEY,
    tweet_id NUMERIC NOT NULL UNIQUE,
    tweet_text VARCHAR(256) NOT NULL,
    timestamp TIMESTAMP DEFAULT '1970-01-01 00:00:00' NOT NULL
);